### ISSUE TITLE
Mobile (android support)?

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [Victa/curtain.js#1]
Great plugin! Really like the effect an IE support.
But on my Mobile (Android) it does not work, any chance for mobile support?

**Comment by Victa** [comment]
Yes, it's not easy to deal with fixed position on mobile.
I believe it's impossible currently to scroll on android device? I'm right? (I haven't Android... :-/ )

I'll work on today or tomorrow. At least to allow the user to scroll in the webpage.

Thanks

**Comment by Victa** [comment]
Partially fixed.
Works on Chrome for Android.

Need more works for the default browser.

**Comment by DESIGNfromWITHIN** [comment]
Works on Opera browser now (scrolling, no curtain effect).
Scrolling does not work in default browser, scrolling works on touch, but when you release the finger from screen, it goes back to top....
