### ISSUE TITLE
IE7,8 not work

### ISSUE THREAD

**Issue by kenjicool** [Victa/curtain.js#13]
It seems the problem happen after the last few updates on curtain.js.
(Problem should start from the curtain.js version 1.3)
Try with the older version of curtain.js and it works quite well.

The problem easily found, just use IE7 or 8 and go to the demo link and u will see the page wholly dead without any scrolling.

Anyone can provide updates on this issue?

**Comment by atblue** [comment]
Yeah, so close to being able to use this but can't figure out the IE8 issue .. i'm ok without IE7 for this, but 8 is needed. Would be lovely if someone could provide some assistance?

**Comment by Victa** [comment]
I'll no longer support IE7 (sorry)
