### ISSUE TITLE
Add back to top menu button?

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [Victa/curtain.js#2]
How about adding a back top top (first slide) button?

**Comment by Victa** [comment]
You can.

Simply add an id attribute to your first panel:

```
<ol class="curtains">
    <li id="myfirstpanel" class="cover"> 
        your content
    </li>
    [...]
</ol>
```

Then you can add a link anywhere to your first panel like:

```
<a href="#myfirstpanel" class="myawesomelink">Go to first panel</a>
```

**Comment by DESIGNfromWITHIN** [comment]
I am sorry, but this not seem to work...
It only works the first time, the the #myfirstpanel is added to the URL and the link does not work anymore...

**Comment by DESIGNfromWITHIN** [comment]
Maybe use jQuery to remove #myfirstpanel from the URL just after the link is clicked?

**Comment by Victa** [comment]
Fixed and I have also added a new option to Curtain.js

#### Example:

Your curtains list :

```
<ol class="curtains">
    <li id="myfirstpanel" class="cover"> 
        your content
    </li>
    [...]
</ol>
```

And your link with a specific class used by the plugin :

```
<a href="#myfirstpanel" class="curtain-links">Go to first panel</a>
```

And to launch the plugin with the new option:

```
$(function () {
    $('.curtains').curtain({
        scrollSpeed: 600,
        controls: '.menu',
        curtainLinks: '.curtain-links'
    });
});
```

Be careful, I have renamed the option 'menu' to 'controls' and delete the jQuery selector ...

**Comment by marmolajpu** [comment]
wooow Thanks thanks thanks!
