### ISSUE TITLE
How to load new block with ajax?

### ISSUE THREAD

**Issue by Tusko** [Victa/curtain.js#36]
I would like to load new blocks with ajax, when scroll will be in some needed position.

After load this blocks, how I can recalculate all?

And how to change parent's block height (when blocks with class="step" were loaded)?

Thank You, Sorry for my English

**Comment by catalinmiron** [comment]
Hi,

Can you provide an example **?** From what i saw, there is no option to re-init the curtain, so, we need to recall the curtain after inserting a list item.

> https://github.com/Victa/curtain.js/blob/development/v2.0/curtain.js#L305
> https://github.com/Victa/curtain.js/blob/development/v2.0/curtain.js#L354

**Comment by jnz31** [comment]
recall works just fine.
