### ISSUE TITLE
Site breaks

### ISSUE THREAD

**Issue by vmahabir** [Victa/curtain.js#40]
getting this message in browser console: 

"TypeError: self.$elDatas[self.currentIndex] is undefined"

Site has a responsive layout. Because of the repositioning of the responsive elements im guessing that the overall height is screwed up and breaks. Does anyone has this problem?

**Comment by vmahabir** [comment]
The style "hidden" is popping up and makes the content invisible. With element inspector i deleted the styles and it was visible again but scrolling was broken.

**Comment by jnz31** [comment]
i had the same issue and i fixed it like so:
replace line 473 `self.currentIndex = self.$current.index();` with `self.currentIndex = self.$current.prevAll().length;`

**Comment by gutierrezalex** [comment]
I was getting this error on FF, and looking at the pull request, it seems this one has not been merged, https://github.com/puneetsl/curtain.js/commit/e3a8814ad244537612bdafebd91b4877a391f965
