### ISSUE TITLE
Text under curtain

### ISSUE THREAD

**Issue by alexcamlo** [Victa/curtain.js#8]
Hi, I'm using your plugin in a website I'm developing and everything works perfect except that when in one of the curtains the text is longer than the viewport, the curtain cuts it instead of letting scroll down till the text finishes like in your plugin website (http://curtain.victorcoulon.fr/). I've really tried to solve it by myself but I'm struggling with it. I don't know if it's much to ask to you if you can look at the code and tell me where I'm going wrong. 
The website is http://www.epse.es/umhfest12 and in the 3rd curtain "Bases" is where I have the problem of the cutted text.

Solved. I just had to not write class="cover" in the li.

Sorry for the bothering.

thank you for your time and help in advance.

**Comment by Victa** [comment]
Perfect :)
